imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    strict_variables: "%kernel.debug%"
    cache: "%kernel.cache_dir%/twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.root_dir%/../var/data/database.sqlite"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lexik_jwt_authentication:
    private_key_path:   '%kernel.root_dir%/../var/jwt/private.pem'
    public_key_path:    '%kernel.root_dir%/../var/jwt/public.pem'
    pass_phrase:        foobar

fos_rest:
#    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/(js|css|images|vendor|bundles).+$, priorities: ['application/javascript', 'text/css', '*/*'], prefer_extension: false }
            - { path: ^/(.+)[\.html]$, priorities: ['html'], fallback_format: html, prefer_extension: false }
            - { path: ^/(.+)$, priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: ^/$, priorities: ['html'], fallback_format: html, prefer_extension: false }
    view:
        mime_types:
            json:
              - 'application/json'
              - 'application/json;version=1.0'
              - 'application/json;version=1.1'
        view_response_listener: 'force'
        formats:
            xml:  false
            json: true
        templating_formats:
            html: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    versioning:
        enabled: true
        resolvers:
            query:
                enabled: false
            custom_header:
                enabled: false
            media_type:
                enabled: true
    routing_loader:
        default_format: null
        include_format: true

jms_serializer:
    visitors:
        json:
            options: [JSON_UNESCAPED_SLASHES, JSON_UNESCAPED_UNICODE]
    handlers:
        datetime:
            default_format: "Y-m-d\\TH:i:sP"

